
[project]
description = "Python decorators as a general utility collection"
authors = [ { name = "Mr. Mattie" , email = "mattie@codermattie.net" } ]

homepage = "https://github.com/bitcathedrals/decorators/"
repository = "https://github.com/bitcathedrals/decorators.git"
